import { Sora } from "next/font/google";
import type { Metadata } from "next";

import Header from "@/layout/Header";
import TopLeftImg from "@/modules/TopLeftImg";
import Nav from "@/modules/Nav";

import "./globals.css";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`page bg-site text-white bg-cover bg-no-repeat ${sora.className} font-sora relative`}
      >
        <TopLeftImg />
        <Nav />
        <Header />
        {children}
      </body>
    </html>
  );
}
